import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Store, UserAccount, UserRole, SalaryPayment, Expense, Sale } from '../types';
import { 
  db, 
  collection, 
  query, 
  where, 
  onSnapshot, 
  doc, 
  setDoc, 
  deleteDoc, 
  updateDoc,
  getDocs,
  handleFirestoreError,
  OperationType 
} from '../lib/firebase';
import { UniversalBackButton } from './UniversalBackButton';
import { ReceiptModal } from './ReceiptModal';
import { 
  Users, 
  Activity, 
  Clock, 
  Wifi, 
  WifiOff, 
  CheckCircle2, 
  AlertCircle, 
  Calendar, 
  Search, 
  Download,
  Calculator,
  DollarSign,
  Trash2,
  Plus,
  Edit3,
  KeyRound,
  ShieldCheck,
  UserPlus,
  Sparkles,
  RefreshCw,
  Coins,
  Receipt,
  CreditCard,
  Banknote,
  Printer,
  ChevronLeft,
  ChevronRight,
  History,
  ArrowRight,
  Wallet,
  Check,
  X,
  FileText,
  Undo2,
  PackageCheck,
  Eye,
  Radio,
  TrendingUp,
  UserCheck,
  UserX
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface StaffSessionsViewProps {
  store: Store;
  currentUser: UserAccount;
  onBack: () => void;
}

export const StaffSessionsView: React.FC<StaffSessionsViewProps> = ({
  store,
  currentUser,
  onBack
}) => {
  const [staffList, setStaffList] = useState<UserAccount[]>([]);
  const [salesList, setSalesList] = useState<Sale[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(false);
  const [notification, setNotification] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  // Modal for inspecting bills generated by a session or staff member
  const [viewingBillsModal, setViewingBillsModal] = useState<{
    title: string;
    subtitle: string;
    staffName: string;
    role: string;
    isOnline: boolean;
    counterInfo?: string;
    sales: Sale[];
    totalBills: number;
    totalRevenue: number;
  } | null>(null);

  // Modal for previewing/printing a customer receipt slip
  const [selectedReceiptSale, setSelectedReceiptSale] = useState<Sale | null>(null);

  // Salary Payments Real-time collection
  const [salaryPayments, setSalaryPayments] = useState<SalaryPayment[]>([]);

  // Current selected month for payroll view (YYYY-MM)
  const [selectedMonth, setSelectedMonth] = useState<string>(() => {
    const d = new Date();
    const yr = d.getFullYear();
    const mo = String(d.getMonth() + 1).padStart(2, '0');
    return `${yr}-${mo}`;
  });

  // Pay Salary Modal State
  const [payingSalaryStaff, setPayingSalaryStaff] = useState<UserAccount | null>(null);
  const [payMonth, setPayMonth] = useState<string>('');
  const [payBaseSalary, setPayBaseSalary] = useState<number>(0);
  const [payBonus, setPayBonus] = useState<number>(0);
  const [payDeduction, setPayDeduction] = useState<number>(0);
  const [payMethod, setPayMethod] = useState<'cash' | 'online'>('cash');
  const [payDate, setPayDate] = useState<string>(() => new Date().toISOString().split('T')[0]);
  const [payNotes, setPayNotes] = useState<string>('');
  const [isProcessingPay, setIsProcessingPay] = useState(false);

  // View / Print Voucher Modal State
  const [viewingPaymentSlip, setViewingPaymentSlip] = useState<SalaryPayment | null>(null);

  // Payment History Modal State
  const [isPaymentHistoryModalOpen, setIsPaymentHistoryModalOpen] = useState(false);
  const [historySearchTerm, setHistorySearchTerm] = useState('');
  const [paymentToDelete, setPaymentToDelete] = useState<SalaryPayment | null>(null);
  const [staffToDelete, setStaffToDelete] = useState<UserAccount | null>(null);

  // Hire Staff Modal State
  const [isHireStaffModalOpen, setIsHireStaffModalOpen] = useState(false);
  const [newStaffName, setNewStaffName] = useState('');
  const [newStaffUsername, setNewStaffUsername] = useState('');
  const [newStaffPassword, setNewStaffPassword] = useState('');
  const [newStaffRole, setNewStaffRole] = useState<string>('cash_counter');
  const [customRoleName, setCustomRoleName] = useState('');
  const [newStaffCounter, setNewStaffCounter] = useState('1');
  const [newStaffSalary, setNewStaffSalary] = useState('');

  // Edit Salary Modal State
  const [editingStaffSalary, setEditingStaffSalary] = useState<UserAccount | null>(null);
  const [updatedSalaryValue, setUpdatedSalaryValue] = useState('');

  const showNotification = (type: 'success' | 'error', message: string) => {
    setNotification({ type, message });
    setTimeout(() => setNotification(null), 4000);
  };

  // Helper for formatted month name
  const getFormattedMonthName = (ym: string) => {
    try {
      const [y, m] = ym.split('-');
      const d = new Date(Number(y), Number(m) - 1, 1);
      return d.toLocaleString('default', { month: 'long', year: 'numeric' });
    } catch {
      return ym;
    }
  };

  const handlePrevMonth = () => {
    const [y, m] = selectedMonth.split('-').map(Number);
    const d = new Date(y, m - 2, 1);
    const newY = d.getFullYear();
    const newM = String(d.getMonth() + 1).padStart(2, '0');
    setSelectedMonth(`${newY}-${newM}`);
  };

  const handleNextMonth = () => {
    const [y, m] = selectedMonth.split('-').map(Number);
    const d = new Date(y, m, 1);
    const newY = d.getFullYear();
    const newM = String(d.getMonth() + 1).padStart(2, '0');
    setSelectedMonth(`${newY}-${newM}`);
  };

  // 1. Real-time listener for staff accounts in this store
  useEffect(() => {
    if (!store?.id) return;
    const qUsers = query(
      collection(db, 'users'),
      where('storeId', '==', store.id)
    );

    const unsub = onSnapshot(qUsers, (snapshot) => {
      const list: UserAccount[] = [];
      snapshot.forEach(docSnap => {
        const u = { id: docSnap.id, ...docSnap.data() } as UserAccount;
        if (u.role !== 'super_admin') {
          list.push(u);
        }
      });
      list.sort((a, b) => (a.name || a.username).localeCompare(b.name || b.username));
      setStaffList(list);
    }, (err) => {
      handleFirestoreError(err, OperationType.LIST, 'users');
    });

    return () => unsub();
  }, [store?.id]);

  // 3. Real-time listener for salary payment records in this store
  useEffect(() => {
    if (!store?.id) return;
    const qPayments = query(
      collection(db, 'salary_payments'),
      where('storeId', '==', store.id)
    );

    const unsub = onSnapshot(qPayments, (snapshot) => {
      const list: SalaryPayment[] = [];
      snapshot.forEach(docSnap => {
        list.push({ id: docSnap.id, ...docSnap.data() } as SalaryPayment);
      });
      list.sort((a, b) => new Date(b.paymentDate || b.createdAt).getTime() - new Date(a.paymentDate || a.createdAt).getTime());
      setSalaryPayments(list);
    }, (err) => {
      handleFirestoreError(err, OperationType.LIST, 'salary_payments');
    });

    return () => unsub();
  }, [store?.id]);

  // 4. Real-time listener for sales in this store to calculate live bills & revenue generated by staff
  useEffect(() => {
    if (!store?.id) return;
    const qSales = query(
      collection(db, 'sales'),
      where('storeId', '==', store.id)
    );

    const unsub = onSnapshot(qSales, (snapshot) => {
      const list: Sale[] = [];
      snapshot.forEach(docSnap => {
        list.push({ id: docSnap.id, ...docSnap.data() } as Sale);
      });
      // Newest sales first
      list.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
      setSalesList(list);
    }, (err) => {
      console.warn('Could not load sales for staff tracking:', err);
    });

    return () => unsub();
  }, [store?.id]);

  // Helper to get formatted role info, icons, and styling badges
  const getRoleInfo = useCallback((role: string) => {
    const r = (role || '').toLowerCase();
    switch (r) {
      case 'cash_counter':
        return {
          label: 'Cashier / Cash Counter',
          shortLabel: 'Cashier',
          badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-200',
          onlineBadgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300',
          icon: Calculator,
          color: 'emerald'
        };
      case 'product_register':
        return {
          label: 'Product Registrar (Inventory)',
          shortLabel: 'Inventory Registrar',
          badgeClass: 'bg-blue-50 text-blue-800 border-blue-200',
          onlineBadgeClass: 'bg-blue-100 text-blue-900 border-blue-300',
          icon: PackageCheck,
          color: 'blue'
        };
      case 'store_admin':
      case 'branch_admin':
      case 'admin':
        return {
          label: 'Store Administrator / Manager',
          shortLabel: 'Store Admin',
          badgeClass: 'bg-amber-50 text-amber-800 border-amber-200',
          onlineBadgeClass: 'bg-amber-100 text-amber-900 border-amber-300',
          icon: ShieldCheck,
          color: 'amber'
        };
      case 'customer_price_checker':
        return {
          label: 'Customer Price Kiosk',
          shortLabel: 'Price Kiosk',
          badgeClass: 'bg-purple-50 text-purple-800 border-purple-200',
          onlineBadgeClass: 'bg-purple-100 text-purple-900 border-purple-300',
          icon: Sparkles,
          color: 'purple'
        };
      default:
        return {
          label: role ? role.replace(/_/g, ' ') : 'Staff Member',
          shortLabel: role ? role.replace(/_/g, ' ') : 'Staff',
          badgeClass: 'bg-slate-50 text-slate-800 border-slate-200',
          onlineBadgeClass: 'bg-slate-100 text-slate-900 border-slate-300',
          icon: Users,
          color: 'slate'
        };
    }
  }, []);

  // Check if a sale was generated by a specific staff member
  const isSaleByStaff = useCallback((sale: Sale, username?: string, userId?: string) => {
    if (!sale) return false;
    const u = username ? username.trim().toLowerCase() : '';
    const uid = userId ? userId.trim().toLowerCase() : '';
    const saleCashier = sale.cashierUsername ? sale.cashierUsername.trim().toLowerCase() : '';
    const saleCounterId = sale.counterId ? sale.counterId.trim().toLowerCase() : '';

    if (u && (saleCashier === u || saleCounterId === u)) return true;
    if (uid && (saleCounterId === uid || saleCashier === uid)) return true;
    return false;
  }, []);

  // Calculate lifetime bills and revenue for a staff member across all sales
  const getStaffLifetimeSalesStats = useCallback((username: string, userId?: string) => {
    const staffSales = salesList.filter(s => isSaleByStaff(s, username, userId));
    const count = staffSales.length;
    const revenue = staffSales.reduce((sum, s) => sum + (Number(s.totalAmount) || 0), 0);
    return { count, revenue, sales: staffSales };
  }, [salesList, isSaleByStaff]);

  // Overall totals across store
  const totalBillsGeneratedAllStaff = useMemo(() => {
    return salesList.length;
  }, [salesList]);

  const totalRevenueGeneratedAllStaff = useMemo(() => {
    return salesList.reduce((sum, s) => sum + (Number(s.totalAmount) || 0), 0);
  }, [salesList]);

  // Total monthly payroll budget calculation
  const totalMonthlyPayroll = useMemo(() => {
    return staffList.reduce((sum, u) => sum + (Number(u.salary) || 0), 0);
  }, [staffList]);

  // Payments for selected month
  const paymentsForSelectedMonth = useMemo(() => {
    return salaryPayments.filter(p => p.month === selectedMonth);
  }, [salaryPayments, selectedMonth]);

  // Map of staffId -> SalaryPayment for the active month
  const staffPaymentMap = useMemo(() => {
    const map = new Map<string, SalaryPayment>();
    paymentsForSelectedMonth.forEach(p => {
      map.set(p.staffId, p);
    });
    return map;
  }, [paymentsForSelectedMonth]);

  // Sum of salaries actually paid & deducted for this month
  const totalPaidThisMonth = useMemo(() => {
    return paymentsForSelectedMonth.reduce((sum, p) => sum + (Number(p.amountPaid) || 0), 0);
  }, [paymentsForSelectedMonth]);

  // Count of staff paid this month
  const paidStaffCount = useMemo(() => {
    return paymentsForSelectedMonth.length;
  }, [paymentsForSelectedMonth]);

  // Count of staff pending payment this month
  const pendingStaffCount = useMemo(() => {
    return Math.max(0, staffList.length - paidStaffCount);
  }, [staffList.length, paidStaffCount]);

  // Sum of pending salaries yet to be paid for this month
  const totalPendingThisMonth = useMemo(() => {
    return staffList.reduce((sum, u) => {
      if (staffPaymentMap.has(u.id)) return sum;
      return sum + (Number(u.salary) || 0);
    }, 0);
  }, [staffList, staffPaymentMap]);

  // Filtered staff list
  const filteredStaff = staffList.filter(s => {
    if (!searchTerm.trim()) return true;
    const term = searchTerm.toLowerCase();
    return (
      s.name.toLowerCase().includes(term) ||
      s.username.toLowerCase().includes(term) ||
      s.role.toLowerCase().includes(term) ||
      (s.counterNumber && s.counterNumber.includes(term))
    );
  });

  // Hire New Staff Member with Salary
  const handleHireStaff = async (e: React.FormEvent) => {
    e.preventDefault();
    const name = newStaffName.trim();
    const username = newStaffUsername.trim().toLowerCase();
    const password = newStaffPassword.trim();
    const salary = Number(newStaffSalary) || 0;

    let finalRole = newStaffRole;
    if (newStaffRole === 'custom') {
      const typedRole = customRoleName.trim();
      if (!typedRole) {
        showNotification('error', 'Please type a custom role name.');
        return;
      }
      finalRole = typedRole.toLowerCase().replace(/\s+/g, '_');
    }

    if (!name || !username || !password) {
      showNotification('error', 'Please provide staff name, username, and password.');
      return;
    }

    setLoading(true);
    try {
      // Check username uniqueness
      const existingQuery = query(collection(db, 'users'), where('username', '==', username));
      const snap = await getDocs(existingQuery);
      if (!snap.empty) {
        showNotification('error', `Username "${username}" is already taken.`);
        setLoading(false);
        return;
      }

      const userDocRef = doc(collection(db, 'users'));
      const newStaffAccount: UserAccount = {
        id: userDocRef.id,
        storeId: store.id,
        storeName: store.name,
        parentStoreId: store.parentStoreId || store.id,
        role: finalRole,
        username,
        password,
        name,
        counterNumber: finalRole === 'cash_counter' ? newStaffCounter : undefined,
        salary,
        salaryFrequency: 'monthly',
        createdAt: new Date().toISOString()
      };

      await setDoc(userDocRef, newStaffAccount);

      showNotification('success', `Staff member ${name} (${finalRole.replace(/_/g, ' ')}) hired with monthly salary of Rs. ${salary.toLocaleString()}!`);
      setIsHireStaffModalOpen(false);
      setNewStaffName('');
      setNewStaffUsername('');
      setNewStaffPassword('');
      setNewStaffSalary('');
      setCustomRoleName('');
      setNewStaffRole('cash_counter');
    } catch (err: any) {
      console.error(err);
      showNotification('error', 'Failed to hire staff: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  // Update Staff Salary
  const handleSaveSalary = async () => {
    if (!editingStaffSalary) return;

    // Strict rule: Branch Admin cannot change their own salary
    if (currentUser.role === 'branch_admin' && (editingStaffSalary.id === currentUser.id || editingStaffSalary.role === 'branch_admin')) {
      showNotification('error', 'Branch Admins cannot change their own salary. Only the Store Admin can set branch admin salary.');
      return;
    }

    const salary = Number(updatedSalaryValue);
    if (isNaN(salary) || salary < 0) {
      showNotification('error', 'Please enter a valid salary amount.');
      return;
    }

    setLoading(true);
    try {
      const userRef = doc(db, 'users', editingStaffSalary.id);
      await updateDoc(userRef, { 
        salary,
        salaryFrequency: 'monthly'
      });

      showNotification('success', `Salary for ${editingStaffSalary.name} updated to Rs. ${salary.toLocaleString()}/month!`);
      setEditingStaffSalary(null);
      setUpdatedSalaryValue('');
    } catch (err: any) {
      console.error(err);
      showNotification('error', 'Failed to update salary: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  // Delete Staff Account
  const confirmDeleteStaff = async () => {
    if (!staffToDelete) return;

    setLoading(true);
    try {
      await deleteDoc(doc(db, 'users', staffToDelete.id));
      showNotification('success', `Staff account for "${staffToDelete.name}" deleted.`);
      setStaffToDelete(null);
    } catch (err: any) {
      console.error(err);
      showNotification('error', 'Failed to delete staff: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  // Open Pay Salary Modal
  const handleOpenPayModal = (staff: UserAccount) => {
    // Check permission: Branch Admin cannot pay their own salary
    if (currentUser.role === 'branch_admin' && (staff.id === currentUser.id || staff.role === 'branch_admin')) {
      showNotification('error', 'Branch Admins cannot pay their own salary. Only the Store Admin can disburse branch admin salary.');
      return;
    }

    const base = Number(staff.salary) || 0;
    setPayingSalaryStaff(staff);
    setPayMonth(selectedMonth);
    setPayBaseSalary(base);
    setPayBonus(0);
    setPayDeduction(0);
    setPayMethod('cash');
    setPayDate(new Date().toISOString().split('T')[0]);
    setPayNotes('');
  };

  // Execute Salary Payment (Creates SalaryPayment record and Expense record to deduct money)
  const handleExecuteSalaryPayment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!payingSalaryStaff || !store) return;

    const base = Number(payBaseSalary) || 0;
    const bonus = Number(payBonus) || 0;
    const deduction = Number(payDeduction) || 0;
    const netAmount = Math.max(0, base + bonus - deduction);

    if (netAmount <= 0) {
      showNotification('error', 'Net salary payout must be greater than Rs. 0.');
      return;
    }

    const monthName = getFormattedMonthName(payMonth);
    setIsProcessingPay(true);

    try {
      const payRef = doc(collection(db, 'salary_payments'));
      const expRef = doc(collection(db, 'expenses'));

      const paymentRecord: SalaryPayment = {
        id: payRef.id,
        storeId: store.id,
        parentStoreId: store.parentStoreId || undefined,
        staffId: payingSalaryStaff.id,
        staffName: payingSalaryStaff.name,
        staffRole: payingSalaryStaff.role,
        staffUsername: payingSalaryStaff.username,
        month: payMonth,
        monthName: monthName,
        baseSalary: base,
        bonusAmount: bonus,
        deductionAmount: deduction,
        amountPaid: netAmount,
        paymentMethod: payMethod,
        paymentDate: payDate,
        notes: payNotes.trim() || `Staff salary for ${monthName}`,
        paidByUsername: currentUser.username,
        paidByName: currentUser.name || currentUser.username,
        expenseId: expRef.id,
        createdAt: new Date().toISOString()
      };

      // Create linked expense record so money is immediately deducted from branch money & net profit!
      const expenseRecord: Expense = {
        id: expRef.id,
        storeId: store.id,
        name: `Staff Salary: ${payingSalaryStaff.name} (${monthName})`,
        amount: netAmount,
        category: 'Staff Salaries & Wages',
        notes: `Salary payout to ${payingSalaryStaff.name} (@${payingSalaryStaff.username}) for ${monthName}. Paid via ${payMethod.toUpperCase()}.${payNotes ? ` Ref: ${payNotes}` : ''}`,
        date: payDate,
        paymentMethod: payMethod,
        timestamp: new Date().toISOString(),
        recordedBy: currentUser.username,
        salaryPaymentId: payRef.id
      };

      await setDoc(payRef, paymentRecord);
      await setDoc(expRef, expenseRecord);

      showNotification('success', `Rs. ${netAmount.toLocaleString()} paid to ${payingSalaryStaff.name} (${monthName}) and deducted from money!`);
      setPayingSalaryStaff(null);
      setViewingPaymentSlip(paymentRecord);
    } catch (err: any) {
      console.error(err);
      showNotification('error', 'Failed to disburse salary: ' + err.message);
    } finally {
      setIsProcessingPay(false);
    }
  };

  // Void / Revert a Salary Payment and restore money
  const handleVoidSalaryPayment = async (payment: SalaryPayment) => {
    setLoading(true);
    try {
      await deleteDoc(doc(db, 'salary_payments', payment.id));
      if (payment.expenseId) {
        await deleteDoc(doc(db, 'expenses', payment.expenseId));
      } else {
        const qExp = query(collection(db, 'expenses'), where('salaryPaymentId', '==', payment.id));
        const expSnap = await getDocs(qExp);
        for (const d of expSnap.docs) {
          await deleteDoc(d.ref);
        }
      }
      showNotification('success', `Salary payment of Rs. ${payment.amountPaid.toLocaleString()} for ${payment.staffName} was reverted and money restored!`);
      setPaymentToDelete(null);
    } catch (err: any) {
      console.error(err);
      showNotification('error', 'Failed to revert salary payment: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-slate-50 flex flex-col font-sans">
      {/* Top Action Header */}
      <div className="bg-white border-b border-slate-200 sticky top-16 z-30 shadow-2xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3.5 flex flex-wrap items-center justify-between gap-3">
          
          <div className="flex items-center gap-3">
            <UniversalBackButton onBack={onBack} label="Back to Dashboard" />
            
            <div className="h-6 w-px bg-slate-200 hidden sm:block" />

            <div className="flex items-center gap-2.5">
              <div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center shadow-sm">
                <Users className="w-5 h-5" />
              </div>
              <div>
                <h1 className="text-base font-black text-slate-900 leading-tight">
                  Staff & Salaries
                </h1>
                <p className="text-[11px] text-slate-500 font-medium">
                  Hire branch staff, configure monthly salaries & track salary disbursements
                </p>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2.5">
            <button
              type="button"
              onClick={() => setIsHireStaffModalOpen(true)}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs transition-colors cursor-pointer shadow-xs"
            >
              <UserPlus className="w-3.5 h-3.5" />
              <span>Hire New Staff</span>
            </button>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 w-full space-y-6">

        {/* Notification Toast */}
        <AnimatePresence>
          {notification && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className={`p-4 rounded-2xl flex items-center justify-between text-xs font-bold shadow-xs border ${
                notification.type === 'success'
                  ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                  : 'bg-red-50 text-red-800 border-red-200'
              }`}
            >
              <span>{notification.message}</span>
              <button onClick={() => setNotification(null)} className="cursor-pointer ml-4">✕</button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* STAFF ROSTER & SALARIES */}
          <div className="space-y-6">
            
            {/* Top Toolbar: Month Picker & Actions */}
            <div className="flex flex-wrap items-center justify-between gap-3 bg-white p-4 rounded-2xl border border-slate-200 shadow-2xs">
              <div className="flex items-center gap-2">
                <div className="flex items-center bg-slate-100 p-1 rounded-xl border border-slate-200">
                  <button
                    type="button"
                    onClick={handlePrevMonth}
                    className="p-1.5 hover:bg-white text-slate-700 rounded-lg transition-all cursor-pointer shadow-2xs"
                    title="Previous Month"
                  >
                    <ChevronLeft className="w-4 h-4" />
                  </button>
                  <div className="flex items-center gap-2 px-3 py-1">
                    <Calendar className="w-4 h-4 text-emerald-600" />
                    <span className="font-black text-xs text-slate-900 tracking-wide min-w-[120px] text-center">
                      {getFormattedMonthName(selectedMonth)}
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={handleNextMonth}
                    className="p-1.5 hover:bg-white text-slate-700 rounded-lg transition-all cursor-pointer shadow-2xs"
                    title="Next Month"
                  >
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>

                {selectedMonth !== `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}` && (
                  <button
                    type="button"
                    onClick={() => {
                      const d = new Date();
                      setSelectedMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
                    }}
                    className="text-[11px] font-bold text-emerald-700 hover:text-emerald-800 bg-emerald-50 px-2.5 py-1.5 rounded-xl border border-emerald-200 cursor-pointer"
                  >
                    Current Month
                  </button>
                )}
              </div>

              <div className="flex items-center gap-2.5">
                <button
                  type="button"
                  onClick={() => setIsPaymentHistoryModalOpen(true)}
                  className="px-3.5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 border border-slate-200"
                >
                  <History className="w-4 h-4 text-slate-600" />
                  <span>Payment Vouchers ({salaryPayments.length})</span>
                </button>

                <button
                  type="button"
                  onClick={() => setIsHireStaffModalOpen(true)}
                  className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-black shadow-sm cursor-pointer transition-all flex items-center gap-1.5"
                >
                  <UserPlus className="w-4 h-4" />
                  <span>Hire Staff & Set Salary</span>
                </button>
              </div>
            </div>

            {/* Monthly Payroll & Payment Summary Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              
              {/* Card 1: Total Payroll Budget */}
              <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-2xs">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">
                    Monthly Salary Budget
                  </span>
                  <div className="w-8 h-8 rounded-xl bg-slate-100 text-slate-600 flex items-center justify-center">
                    <Users className="w-4 h-4" />
                  </div>
                </div>
                <div className="text-2xl font-black text-slate-900 mt-2 font-mono">
                  Rs. {totalMonthlyPayroll.toLocaleString()}
                </div>
                <div className="text-[11px] text-slate-500 mt-1 font-medium">
                  Configured across {staffList.length} staff member{staffList.length === 1 ? '' : 's'}
                </div>
              </div>

              {/* Card 2: Salaries Paid & Deducted From Money */}
              <div className="bg-emerald-50/60 p-5 rounded-2xl border border-emerald-200/80 shadow-2xs">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold text-emerald-800 uppercase tracking-wider flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                    Paid & Deducted From Money
                  </span>
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-300">
                    {paidStaffCount} Paid
                  </span>
                </div>
                <div className="text-2xl font-black text-emerald-700 mt-2 font-mono">
                  Rs. {totalPaidThisMonth.toLocaleString()}
                </div>
                <div className="text-[11px] text-emerald-700/90 mt-1 font-medium">
                  Deducted from branch cash & recorded in expense ledger
                </div>
              </div>

              {/* Card 3: Pending Payouts (Not Yet Deducted) */}
              <div className="bg-amber-50/60 p-5 rounded-2xl border border-amber-200/80 shadow-2xs">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold text-amber-800 uppercase tracking-wider flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5 text-amber-600" />
                    Pending Payouts
                  </span>
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-amber-100 text-amber-800 border border-amber-300">
                    {pendingStaffCount} Awaiting
                  </span>
                </div>
                <div className="text-2xl font-black text-amber-700 mt-2 font-mono">
                  Rs. {totalPendingThisMonth.toLocaleString()}
                </div>
                <div className="text-[11px] text-amber-700/90 mt-1 font-medium">
                  Not yet deducted until salary is paid in cash or online
                </div>
              </div>

            </div>

            {/* Staff Search Filter */}
            <div className="flex items-center gap-3">
              <div className="relative flex-1 max-w-sm">
                <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Filter staff by name, username or counter..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-white border border-slate-200 rounded-xl text-xs font-medium text-slate-900 focus:outline-none focus:border-emerald-500 shadow-2xs"
                />
              </div>
            </div>

            {/* Staff & Salaries Table */}
            <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-xs">
              {filteredStaff.length === 0 ? (
                <div className="p-12 text-center text-slate-400">
                  <Users className="w-12 h-12 mx-auto text-slate-300 mb-2" />
                  <p className="font-bold text-slate-700 text-base">No Staff Found</p>
                  <p className="text-xs text-slate-400 mt-1">Click "Hire Staff & Set Salary" to register team members.</p>
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs border-collapse">
                    <thead className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200">
                      <tr>
                        <th className="p-3.5">Staff Member</th>
                        <th className="p-3.5">Role & Counter</th>
                        <th className="p-3.5">Base Salary</th>
                        <th className="p-3.5">Status ({getFormattedMonthName(selectedMonth)})</th>
                        <th className="p-3.5">Deducted From Money</th>
                        <th className="p-3.5 text-center">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {filteredStaff.map((staff) => {
                        const payment = staffPaymentMap.get(staff.id);
                        const isPaid = Boolean(payment);

                        return (
                          <tr key={staff.id} className="hover:bg-slate-50 transition-colors">
                            {/* Staff Name & Username */}
                            <td className="p-3.5">
                              <div className="font-bold text-slate-900 text-sm">{staff.name}</div>
                              <div className="text-[11px] text-slate-400 font-mono">@{staff.username}</div>
                            </td>

                            {/* Role & Counter */}
                            <td className="p-3.5">
                              <div className="flex items-center gap-1.5 flex-wrap">
                                <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-slate-100 text-slate-700 font-bold text-[10px] uppercase border border-slate-200">
                                  {staff.role.replace('_', ' ')}
                                </span>
                                {staff.counterNumber && (
                                  <span className="font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200 text-[10px]">
                                    Counter #{staff.counterNumber}
                                  </span>
                                )}
                              </div>
                            </td>

                            {/* Base Monthly Salary */}
                            <td className="p-3.5 font-bold font-mono text-sm text-slate-900">
                              {staff.salary ? (
                                `Rs. ${Number(staff.salary).toLocaleString()}`
                              ) : (
                                <span className="text-slate-400 font-normal italic text-xs">Not configured</span>
                              )}
                            </td>

                            {/* Payment Status for Selected Month */}
                            <td className="p-3.5">
                              {isPaid && payment ? (
                                <div className="space-y-1">
                                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 font-bold text-[10px] border border-emerald-300">
                                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                                    <span>Paid Rs. {payment.amountPaid.toLocaleString()}</span>
                                  </span>
                                  <div className="text-[10px] text-slate-500 font-medium">
                                    {payment.paymentDate} • <span className="uppercase">{payment.paymentMethod}</span>
                                  </div>
                                </div>
                              ) : (
                                <div className="space-y-1">
                                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-50 text-amber-800 font-bold text-[10px] border border-amber-300">
                                    <Clock className="w-3.5 h-3.5 text-amber-600" />
                                    <span>Payment Pending</span>
                                  </span>
                                  <div className="text-[10px] text-slate-400">
                                    Due for {getFormattedMonthName(selectedMonth)}
                                  </div>
                                </div>
                              )}
                            </td>

                            {/* Deducted From Money */}
                            <td className="p-3.5">
                              {isPaid && payment ? (
                                <span className="inline-flex items-center gap-1 font-mono font-bold text-xs text-red-700 bg-red-50 px-2 py-0.5 rounded border border-red-200">
                                  -Rs. {payment.amountPaid.toLocaleString()}
                                </span>
                              ) : (
                                <span className="text-slate-400 italic text-[11px]">
                                  Pending payment
                                </span>
                              )}
                            </td>

                            {/* Actions Column */}
                            <td className="p-3.5 text-center">
                              <div className="flex items-center justify-center gap-2">
                                
                                {/* If NOT paid: Primary Pay Salary Button */}
                                {!isPaid && (
                                  <button
                                    type="button"
                                    onClick={() => handleOpenPayModal(staff)}
                                    className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-black shadow-xs transition-all cursor-pointer flex items-center gap-1"
                                    title={`Disburse salary for ${getFormattedMonthName(selectedMonth)}`}
                                  >
                                    <Banknote className="w-3.5 h-3.5" />
                                    <span>Pay Salary</span>
                                  </button>
                                )}

                                {/* If PAID: View Slip / Voucher Button */}
                                {isPaid && payment && (
                                  <>
                                    <button
                                      type="button"
                                      onClick={() => setViewingPaymentSlip(payment)}
                                      className="px-2.5 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-800 border border-blue-200 rounded-xl text-xs font-bold transition-colors cursor-pointer flex items-center gap-1"
                                      title="View / Print Salary Voucher"
                                    >
                                      <Receipt className="w-3.5 h-3.5" />
                                      <span>Slip</span>
                                    </button>

                                    <button
                                      type="button"
                                      onClick={() => setPaymentToDelete(payment)}
                                      className="p-1.5 text-slate-400 hover:text-amber-700 hover:bg-amber-50 rounded-lg transition-colors cursor-pointer"
                                      title="Void this salary payment and restore money"
                                    >
                                      <Undo2 className="w-3.5 h-3.5" />
                                    </button>
                                  </>
                                )}

                                {/* Edit Salary Config Button */}
                                {currentUser.role === 'branch_admin' && (staff.id === currentUser.id || staff.role === 'branch_admin') ? (
                                  <span 
                                    className="px-2 py-1 bg-slate-100 text-slate-500 rounded-lg text-[10px] font-bold border border-slate-200"
                                    title="Branch Admin salary is set by Store Admin and cannot be edited by yourself"
                                  >
                                    Store Admin Set
                                  </span>
                                ) : (
                                  <button
                                    type="button"
                                    onClick={() => {
                                      setEditingStaffSalary(staff);
                                      setUpdatedSalaryValue(String(staff.salary || ''));
                                    }}
                                    className="p-1.5 text-slate-500 hover:text-emerald-700 hover:bg-emerald-50 rounded-lg transition-colors cursor-pointer"
                                    title="Edit Base Monthly Salary"
                                  >
                                    <Edit3 className="w-3.5 h-3.5" />
                                  </button>
                                )}

                                {/* Delete Staff Account */}
                                {!(currentUser.role === 'branch_admin' && (staff.id === currentUser.id || staff.role === 'branch_admin')) && (
                                  <button
                                    type="button"
                                    onClick={() => setStaffToDelete(staff)}
                                    className="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors cursor-pointer"
                                    title="Delete staff account"
                                  >
                                    <Trash2 className="w-3.5 h-3.5" />
                                  </button>
                                )}
                              </div>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

          </div>

      </div>

      {/* MODAL: HIRE NEW STAFF */}
      <AnimatePresence>
        {isHireStaffModalOpen && (
          <div className="fixed inset-0 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 z-50">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-md w-full p-6 shadow-2xl border border-slate-200 space-y-4"
            >
              <div className="flex items-center justify-between border-b border-slate-200 pb-3">
                <div className="flex items-center gap-2">
                  <UserPlus className="w-5 h-5 text-emerald-600" />
                  <h3 className="text-base font-bold text-slate-900">Hire Branch Staff</h3>
                </div>
                <button
                  onClick={() => setIsHireStaffModalOpen(false)}
                  className="text-slate-400 hover:text-slate-700 cursor-pointer"
                >
                  ✕
                </button>
              </div>

              <form onSubmit={handleHireStaff} className="space-y-3.5 text-xs">
                <div>
                  <label className="block font-bold text-slate-700 uppercase mb-1">Staff Full Name</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Ali Ahmed"
                    value={newStaffName}
                    onChange={(e) => setNewStaffName(e.target.value)}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:bg-white focus:outline-none focus:border-emerald-500"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-bold text-slate-700 uppercase mb-1">Username</label>
                    <input
                      type="text"
                      required
                      placeholder="e.g. ali_cashier"
                      value={newStaffUsername}
                      onChange={(e) => setNewStaffUsername(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:bg-white focus:outline-none focus:border-emerald-500 font-mono"
                    />
                  </div>

                  <div>
                    <label className="block font-bold text-slate-700 uppercase mb-1">Password</label>
                    <input
                      type="password"
                      required
                      placeholder="••••••••"
                      value={newStaffPassword}
                      onChange={(e) => setNewStaffPassword(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:bg-white focus:outline-none focus:border-emerald-500"
                    />
                  </div>
                </div>

                <div className="space-y-3">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block font-bold text-slate-700 uppercase mb-1">Staff Role</label>
                      <select
                        value={newStaffRole}
                        onChange={(e) => setNewStaffRole(e.target.value)}
                        className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:bg-white focus:outline-none focus:border-emerald-500 cursor-pointer"
                      >
                        <option value="cash_counter">Cash Counter (POS)</option>
                        <option value="product_register">Product Register (Inventory)</option>
                        <option value="customer_price_checker">Price Checker (Kiosk)</option>
                        <option value="branch_admin">Branch Admin / Manager</option>
                        <option value="custom">Type Custom Role...</option>
                      </select>
                    </div>

                    {newStaffRole === 'cash_counter' && (
                      <div>
                        <label className="block font-bold text-slate-700 uppercase mb-1">Counter Number</label>
                        <input
                          type="text"
                          placeholder="1"
                          value={newStaffCounter}
                          onChange={(e) => setNewStaffCounter(e.target.value)}
                          className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:bg-white focus:outline-none focus:border-emerald-500 font-mono"
                        />
                      </div>
                    )}
                  </div>

                  {newStaffRole === 'custom' && (
                    <div className="p-3 bg-emerald-50/50 rounded-2xl border border-emerald-200 space-y-2">
                      <label className="block font-bold text-emerald-900 uppercase">
                        Type Any Custom Role
                      </label>
                      <input
                        type="text"
                        required
                        placeholder="e.g. Security Guard, Supervisor, Stock Restocker, Cleaner, Accountant"
                        value={customRoleName}
                        onChange={(e) => setCustomRoleName(e.target.value)}
                        className="w-full px-3 py-2 bg-white border border-emerald-300 rounded-xl text-slate-900 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500"
                      />
                      <div className="flex flex-wrap gap-1.5 pt-1">
                        <span className="text-[10px] text-slate-500 font-medium self-center">Suggestions:</span>
                        {['Security Guard', 'Store Supervisor', 'Shelf Restocker', 'Cleaner', 'Inventory Specialist', 'Accountant', 'Delivery Rider'].map((sug) => (
                          <button
                            key={sug}
                            type="button"
                            onClick={() => setCustomRoleName(sug)}
                            className="text-[10px] px-2 py-0.5 bg-white hover:bg-emerald-100 text-emerald-800 rounded-lg border border-emerald-200 transition-colors cursor-pointer"
                          >
                            + {sug}
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>

                {/* Monthly Salary Input */}
                <div>
                  <label className="block font-bold text-slate-700 uppercase mb-1 flex items-center justify-between">
                    <span>Monthly Salary (Rs.)</span>
                    <span className="text-[10px] text-emerald-700 lowercase font-normal">Deducted from profit</span>
                  </label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 font-bold text-slate-400">Rs.</span>
                    <input
                      type="number"
                      required
                      min="0"
                      step="500"
                      placeholder="e.g. 35000"
                      value={newStaffSalary}
                      onChange={(e) => setNewStaffSalary(e.target.value)}
                      className="w-full pl-10 pr-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-mono font-bold focus:bg-white focus:outline-none focus:border-emerald-500"
                    />
                  </div>
                </div>

                <div className="pt-2 flex items-center justify-end gap-2">
                  <button
                    type="button"
                    onClick={() => setIsHireStaffModalOpen(false)}
                    className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold transition-colors cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={loading}
                    className="px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold transition-colors cursor-pointer shadow-sm disabled:opacity-50"
                  >
                    {loading ? 'Creating...' : 'Save & Hire Staff'}
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: EDIT SALARY */}
      <AnimatePresence>
        {editingStaffSalary && (
          <div className="fixed inset-0 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 z-50">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-sm w-full p-6 shadow-2xl border border-slate-200 space-y-4"
            >
              <div className="flex items-center justify-between border-b border-slate-200 pb-3">
                <div className="flex items-center gap-2">
                  <DollarSign className="w-5 h-5 text-emerald-600" />
                  <h3 className="text-base font-bold text-slate-900">Update Monthly Salary</h3>
                </div>
                <button
                  onClick={() => setEditingStaffSalary(null)}
                  className="text-slate-400 hover:text-slate-700 cursor-pointer"
                >
                  ✕
                </button>
              </div>

              <div className="space-y-3 text-xs">
                <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                  <div className="font-bold text-slate-900 text-sm">{editingStaffSalary.name}</div>
                  <div className="text-slate-400 font-mono text-[11px]">@{editingStaffSalary.username} • {editingStaffSalary.role.replace('_', ' ')}</div>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 uppercase mb-1">
                    Monthly Base Salary (Rs.)
                  </label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 font-bold text-slate-400">Rs.</span>
                    <input
                      type="number"
                      required
                      min="0"
                      step="500"
                      placeholder="e.g. 40000"
                      value={updatedSalaryValue}
                      onChange={(e) => setUpdatedSalaryValue(e.target.value)}
                      className="w-full pl-10 pr-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-mono font-bold focus:bg-white focus:outline-none focus:border-emerald-500"
                      autoFocus
                    />
                  </div>
                  <p className="text-[10px] text-slate-500 mt-1 font-medium">
                    This salary will be deducted from branch profit calculations in analytics and P&L.
                  </p>
                </div>

                <div className="pt-2 flex items-center justify-end gap-2">
                  <button
                    type="button"
                    onClick={() => setEditingStaffSalary(null)}
                    className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold transition-colors cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    onClick={handleSaveSalary}
                    disabled={loading}
                    className="px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold transition-colors cursor-pointer shadow-sm disabled:opacity-50"
                  >
                    {loading ? 'Saving...' : 'Update Salary'}
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: PAY STAFF SALARY & DEDUCT FROM MONEY */}
      <AnimatePresence>
        {payingSalaryStaff && (
          <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-xs flex items-center justify-center p-4 z-50 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-lg w-full p-6 shadow-2xl border border-slate-200 space-y-4 my-8"
            >
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2.5">
                  <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold">
                    <Banknote className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-black text-slate-900 leading-tight">Pay Staff Salary</h3>
                    <p className="text-xs text-slate-500">
                      Disburse salary and deduct amount from branch money & profit
                    </p>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => setPayingSalaryStaff(null)}
                  className="p-1 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Staff Overview Banner */}
              <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200 flex items-center justify-between gap-3">
                <div>
                  <div className="font-bold text-slate-900 text-sm">{payingSalaryStaff.name}</div>
                  <div className="text-[11px] text-slate-500 font-mono">
                    @{payingSalaryStaff.username} • {payingSalaryStaff.role.replace('_', ' ').toUpperCase()}
                    {payingSalaryStaff.counterNumber ? ` (Counter #${payingSalaryStaff.counterNumber})` : ''}
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Configured Salary</div>
                  <div className="text-base font-black font-mono text-emerald-700">
                    Rs. {(Number(payingSalaryStaff.salary) || 0).toLocaleString()}
                  </div>
                </div>
              </div>

              <form onSubmit={handleExecuteSalaryPayment} className="space-y-4 text-xs">
                
                {/* Month & Payment Date */}
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-bold text-slate-700 uppercase mb-1">
                      Salary For Month
                    </label>
                    <input
                      type="month"
                      required
                      value={payMonth}
                      onChange={(e) => setPayMonth(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-semibold focus:bg-white focus:outline-none focus:border-emerald-500"
                    />
                  </div>

                  <div>
                    <label className="block font-bold text-slate-700 uppercase mb-1">
                      Payment Date
                    </label>
                    <input
                      type="date"
                      required
                      value={payDate}
                      onChange={(e) => setPayDate(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-semibold focus:bg-white focus:outline-none focus:border-emerald-500"
                    />
                  </div>
                </div>

                {/* Base Salary, Bonus, Deductions */}
                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block font-bold text-slate-700 uppercase mb-1">
                      Base Salary (Rs.)
                    </label>
                    <input
                      type="number"
                      required
                      min="0"
                      step="100"
                      value={payBaseSalary}
                      onChange={(e) => setPayBaseSalary(Number(e.target.value))}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-bold font-mono focus:bg-white focus:outline-none focus:border-emerald-500"
                    />
                  </div>

                  <div>
                    <label className="block font-bold text-slate-700 uppercase mb-1 text-emerald-700">
                      + Bonus / OT (Rs.)
                    </label>
                    <input
                      type="number"
                      min="0"
                      step="50"
                      value={payBonus}
                      onChange={(e) => setPayBonus(Number(e.target.value))}
                      className="w-full px-3 py-2 bg-emerald-50/50 border border-emerald-200 rounded-xl text-emerald-900 font-bold font-mono focus:bg-white focus:outline-none focus:border-emerald-500"
                    />
                  </div>

                  <div>
                    <label className="block font-bold text-slate-700 uppercase mb-1 text-red-700">
                      - Deductions (Rs.)
                    </label>
                    <input
                      type="number"
                      min="0"
                      step="50"
                      value={payDeduction}
                      onChange={(e) => setPayDeduction(Number(e.target.value))}
                      className="w-full px-3 py-2 bg-red-50/50 border border-red-200 rounded-xl text-red-900 font-bold font-mono focus:bg-white focus:outline-none focus:border-red-500"
                    />
                  </div>
                </div>

                {/* Calculated Net Payout Preview */}
                <div className="p-4 bg-gradient-to-r from-emerald-600 to-teal-700 text-white rounded-2xl shadow-sm">
                  <div className="flex items-center justify-between">
                    <div>
                      <span className="text-[10px] font-bold text-emerald-200 uppercase tracking-wider block">
                        Net Amount Deducted From Money
                      </span>
                      <div className="text-2xl font-black font-mono mt-0.5">
                        Rs. {Math.max(0, (Number(payBaseSalary) || 0) + (Number(payBonus) || 0) - (Number(payDeduction) || 0)).toLocaleString()}
                      </div>
                    </div>
                    <div className="text-right text-[11px] text-emerald-100 font-medium space-y-0.5">
                      <div>Base: Rs. {(Number(payBaseSalary) || 0).toLocaleString()}</div>
                      <div>Bonus: +Rs. {(Number(payBonus) || 0).toLocaleString()}</div>
                      <div>Deduction: -Rs. {(Number(payDeduction) || 0).toLocaleString()}</div>
                    </div>
                  </div>
                </div>

                {/* Payment Method Selection */}
                <div>
                  <label className="block font-bold text-slate-700 uppercase mb-1.5">
                    Disbursement Method (Money Deduction Channel)
                  </label>
                  <div className="grid grid-cols-2 gap-3">
                    <label className={`flex items-center gap-2.5 p-3 rounded-xl border cursor-pointer transition-all ${
                      payMethod === 'cash' 
                        ? 'bg-emerald-50 border-emerald-500 text-emerald-900 font-bold ring-1 ring-emerald-500' 
                        : 'bg-slate-50 border-slate-200 text-slate-700 hover:bg-slate-100'
                    }`}>
                      <input
                        type="radio"
                        name="payMethod"
                        value="cash"
                        checked={payMethod === 'cash'}
                        onChange={() => setPayMethod('cash')}
                        className="text-emerald-600 focus:ring-emerald-500"
                      />
                      <Banknote className="w-4 h-4 text-emerald-600" />
                      <div>
                        <div className="text-xs font-bold leading-tight">Cash Register</div>
                        <div className="text-[10px] text-slate-500 font-normal">Paid from drawer cash</div>
                      </div>
                    </label>

                    <label className={`flex items-center gap-2.5 p-3 rounded-xl border cursor-pointer transition-all ${
                      payMethod === 'online' 
                        ? 'bg-blue-50 border-blue-500 text-blue-900 font-bold ring-1 ring-blue-500' 
                        : 'bg-slate-50 border-slate-200 text-slate-700 hover:bg-slate-100'
                    }`}>
                      <input
                        type="radio"
                        name="payMethod"
                        value="online"
                        checked={payMethod === 'online'}
                        onChange={() => setPayMethod('online')}
                        className="text-blue-600 focus:ring-blue-500"
                      />
                      <CreditCard className="w-4 h-4 text-blue-600" />
                      <div>
                        <div className="text-xs font-bold leading-tight">Bank / Online</div>
                        <div className="text-[10px] text-slate-500 font-normal">Direct bank transfer</div>
                      </div>
                    </label>
                  </div>
                </div>

                {/* Payment Notes / Reference */}
                <div>
                  <label className="block font-bold text-slate-700 uppercase mb-1">
                    Notes / Reference (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. Salary paid via cash counter, includes 2 hrs overtime"
                    value={payNotes}
                    onChange={(e) => setPayNotes(e.target.value)}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:bg-white focus:outline-none focus:border-emerald-500"
                  />
                </div>

                {/* Expense deduction notice */}
                <div className="flex items-start gap-2 p-3 bg-slate-100 rounded-xl text-slate-600 text-[11px]">
                  <AlertCircle className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
                  <span>
                    Confirming this payment will immediately record a <strong>Staff Salaries & Wages</strong> expense in the store ledger and subtract this amount from the branch realized net profit and cash ledger.
                  </span>
                </div>

                <div className="pt-2 flex items-center justify-end gap-2.5">
                  <button
                    type="button"
                    onClick={() => setPayingSalaryStaff(null)}
                    className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold transition-colors cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={isProcessingPay}
                    className="px-6 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-black shadow-md cursor-pointer transition-all flex items-center gap-2 disabled:opacity-50"
                  >
                    <CheckCircle2 className="w-4 h-4" />
                    <span>{isProcessingPay ? 'Processing Payout...' : 'Confirm & Deduct Salary'}</span>
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: PRINTABLE SALARY PAYMENT VOUCHER / SLIP */}
      <AnimatePresence>
        {viewingPaymentSlip && (
          <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-xs flex items-center justify-center p-4 z-50 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-lg w-full p-6 shadow-2xl border border-slate-200 space-y-5 my-8"
            >
              {/* Slip Action Header */}
              <div className="flex items-center justify-between border-b border-slate-100 pb-3 print:hidden">
                <div className="flex items-center gap-2 text-emerald-700 font-bold text-sm">
                  <Receipt className="w-5 h-5" />
                  <span>Salary Payment Voucher</span>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => window.print()}
                    className="px-3 py-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200 rounded-xl text-xs font-bold transition-colors cursor-pointer flex items-center gap-1.5"
                  >
                    <Printer className="w-4 h-4" />
                    <span>Print Voucher</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setViewingPaymentSlip(null)}
                    className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>

              {/* Printable Voucher Paper */}
              <div id="salary-voucher-slip" className="border-2 border-slate-800 rounded-2xl p-6 bg-white space-y-4 text-slate-900 font-sans">
                
                {/* Store Header */}
                <div className="text-center border-b-2 border-slate-800 pb-3">
                  <h2 className="text-xl font-black uppercase tracking-wider">{store.name}</h2>
                  {store.address && <p className="text-xs text-slate-600">{store.address}</p>}
                  <div className="inline-block mt-1 px-3 py-0.5 bg-slate-900 text-white rounded text-[10px] font-black uppercase tracking-widest">
                    Official Salary Payment Voucher
                  </div>
                </div>

                {/* Voucher Meta */}
                <div className="grid grid-cols-2 gap-2 text-xs border-b border-slate-200 pb-3">
                  <div>
                    <span className="text-slate-500 font-medium">Voucher No: </span>
                    <span className="font-mono font-bold">SAL-{viewingPaymentSlip.id.slice(0, 8).toUpperCase()}</span>
                  </div>
                  <div className="text-right">
                    <span className="text-slate-500 font-medium">Date: </span>
                    <span className="font-bold">{viewingPaymentSlip.paymentDate}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 font-medium">Salary Period: </span>
                    <span className="font-bold text-emerald-800">{viewingPaymentSlip.monthName || getFormattedMonthName(viewingPaymentSlip.month)}</span>
                  </div>
                  <div className="text-right">
                    <span className="text-slate-500 font-medium">Payment Mode: </span>
                    <span className="font-bold uppercase">{viewingPaymentSlip.paymentMethod}</span>
                  </div>
                </div>

                {/* Staff Details */}
                <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 text-xs">
                  <div className="font-bold text-slate-900 text-sm">{viewingPaymentSlip.staffName}</div>
                  <div className="text-[11px] text-slate-500 font-mono">
                    Username: @{viewingPaymentSlip.staffUsername} • Designation: {viewingPaymentSlip.staffRole.replace('_', ' ').toUpperCase()}
                  </div>
                </div>

                {/* Itemized Payout Table */}
                <table className="w-full text-xs border-collapse">
                  <thead>
                    <tr className="border-b border-slate-300 text-slate-600 uppercase text-[10px]">
                      <th className="py-1.5 text-left">Description</th>
                      <th className="py-1.5 text-right">Amount (PKR)</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 font-medium">
                    <tr>
                      <td className="py-2">Base Monthly Salary</td>
                      <td className="py-2 text-right font-mono font-bold">
                        Rs. {viewingPaymentSlip.baseSalary.toLocaleString()}
                      </td>
                    </tr>
                    {Boolean(viewingPaymentSlip.bonusAmount) && (
                      <tr className="text-emerald-700">
                        <td className="py-1.5">+ Overtime & Performance Bonus</td>
                        <td className="py-1.5 text-right font-mono font-bold">
                          +Rs. {(viewingPaymentSlip.bonusAmount || 0).toLocaleString()}
                        </td>
                      </tr>
                    )}
                    {Boolean(viewingPaymentSlip.deductionAmount) && (
                      <tr className="text-red-700">
                        <td className="py-1.5">- Deductions (Leaves / Absences)</td>
                        <td className="py-1.5 text-right font-mono font-bold">
                          -Rs. {(viewingPaymentSlip.deductionAmount || 0).toLocaleString()}
                        </td>
                      </tr>
                    )}
                    <tr className="border-t-2 border-slate-800 text-base font-black">
                      <td className="py-2.5 uppercase tracking-wide">Net Salary Disbursed</td>
                      <td className="py-2.5 text-right font-mono text-emerald-800">
                        Rs. {viewingPaymentSlip.amountPaid.toLocaleString()}
                      </td>
                    </tr>
                  </tbody>
                </table>

                {/* Notes if present */}
                {viewingPaymentSlip.notes && (
                  <div className="text-[11px] text-slate-600 bg-slate-50 p-2.5 rounded-lg border border-slate-200">
                    <span className="font-bold text-slate-700">Remarks: </span>
                    {viewingPaymentSlip.notes}
                  </div>
                )}

                <div className="text-[10px] text-slate-500 border-t border-slate-200 pt-2 flex justify-between">
                  <span>Processed by: {viewingPaymentSlip.paidByName} (@{viewingPaymentSlip.paidByUsername})</span>
                  <span className="text-emerald-700 font-bold">STATUS: DEDUCTED & PAID</span>
                </div>

                {/* Signatures */}
                <div className="grid grid-cols-2 gap-8 pt-8 text-xs text-center border-t border-slate-300">
                  <div>
                    <div className="border-b border-slate-400 mb-1 h-8" />
                    <span className="font-bold text-slate-700">Authorized Manager Signature</span>
                  </div>
                  <div>
                    <div className="border-b border-slate-400 mb-1 h-8" />
                    <span className="font-bold text-slate-700">Employee Signature & Receipt</span>
                  </div>
                </div>

              </div>

              {/* Bottom Buttons */}
              <div className="flex items-center justify-end gap-2 pt-1 print:hidden">
                <button
                  type="button"
                  onClick={() => setViewingPaymentSlip(null)}
                  className="px-5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-xl font-bold text-xs cursor-pointer transition-colors"
                >
                  Close
                </button>
              </div>

            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: PAYMENT HISTORY & VOUCHERS LEDGER */}
      <AnimatePresence>
        {isPaymentHistoryModalOpen && (
          <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-xs flex items-center justify-center p-4 z-50 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-3xl w-full p-6 shadow-2xl border border-slate-200 space-y-4 my-8"
            >
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2.5">
                  <div className="w-10 h-10 rounded-xl bg-blue-100 text-blue-700 flex items-center justify-center font-bold">
                    <History className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-black text-slate-900 leading-tight">Salary Payment History</h3>
                    <p className="text-xs text-slate-500">
                      All salary disbursements recorded and deducted from branch money
                    </p>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => setIsPaymentHistoryModalOpen(false)}
                  className="p-1 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Search Bar */}
              <div className="relative">
                <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Search disbursements by staff name, username, or month..."
                  value={historySearchTerm}
                  onChange={(e) => setHistorySearchTerm(e.target.value)}
                  className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-900 focus:bg-white focus:outline-none focus:border-blue-500"
                />
              </div>

              {/* Payments List Table */}
              <div className="max-h-96 overflow-y-auto border border-slate-200 rounded-2xl overflow-hidden">
                {salaryPayments.length === 0 ? (
                  <div className="p-10 text-center text-slate-400 text-xs">
                    <Receipt className="w-10 h-10 mx-auto text-slate-300 mb-2" />
                    <p className="font-bold text-slate-700">No Salary Payments Recorded Yet</p>
                    <p className="mt-1">When you click "Pay Salary", disbursements will appear here.</p>
                  </div>
                ) : (
                  <table className="w-full text-left text-xs border-collapse">
                    <thead className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200 sticky top-0">
                      <tr>
                        <th className="p-3">Date</th>
                        <th className="p-3">Staff Member</th>
                        <th className="p-3">Month</th>
                        <th className="p-3">Amount</th>
                        <th className="p-3">Method</th>
                        <th className="p-3 text-center">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {salaryPayments
                        .filter(p => {
                          if (!historySearchTerm.trim()) return true;
                          const term = historySearchTerm.toLowerCase();
                          return (
                            p.staffName.toLowerCase().includes(term) ||
                            p.staffUsername.toLowerCase().includes(term) ||
                            p.month.toLowerCase().includes(term) ||
                            (p.monthName && p.monthName.toLowerCase().includes(term))
                          );
                        })
                        .map((p) => (
                          <tr key={p.id} className="hover:bg-slate-50 transition-colors">
                            <td className="p-3 font-mono text-slate-600 whitespace-nowrap">
                              {p.paymentDate}
                            </td>
                            <td className="p-3">
                              <div className="font-bold text-slate-900">{p.staffName}</div>
                              <div className="text-[10px] text-slate-400 font-mono">@{p.staffUsername}</div>
                            </td>
                            <td className="p-3 font-bold text-slate-700 whitespace-nowrap">
                              {p.monthName || getFormattedMonthName(p.month)}
                            </td>
                            <td className="p-3 font-mono font-bold text-emerald-700 whitespace-nowrap">
                              Rs. {p.amountPaid.toLocaleString()}
                            </td>
                            <td className="p-3 uppercase text-[10px] font-bold text-slate-600 whitespace-nowrap">
                              {p.paymentMethod}
                            </td>
                            <td className="p-3 text-center whitespace-nowrap">
                              <div className="flex items-center justify-center gap-1.5">
                                <button
                                  type="button"
                                  onClick={() => setViewingPaymentSlip(p)}
                                  className="px-2.5 py-1 bg-blue-50 hover:bg-blue-100 text-blue-800 rounded-lg text-[11px] font-bold transition-colors cursor-pointer flex items-center gap-1"
                                  title="View Printable Voucher"
                                >
                                  <Receipt className="w-3 h-3" />
                                  <span>Voucher</span>
                                </button>
                                <button
                                  type="button"
                                  onClick={() => setPaymentToDelete(p)}
                                  className="p-1 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors cursor-pointer"
                                  title="Void payment and restore money"
                                >
                                  <Trash2 className="w-3.5 h-3.5" />
                                </button>
                              </div>
                            </td>
                          </tr>
                        ))}
                    </tbody>
                  </table>
                )}
              </div>

              <div className="flex items-center justify-end pt-2">
                <button
                  type="button"
                  onClick={() => setIsPaymentHistoryModalOpen(false)}
                  className="px-5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-xl font-bold text-xs transition-colors cursor-pointer"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: VOID / REVERT SALARY PAYMENT CONFIRMATION */}
      <AnimatePresence>
        {paymentToDelete && (
          <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-xs flex items-center justify-center p-4 z-50">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-sm w-full p-6 shadow-2xl border border-slate-200 space-y-4"
            >
              <div className="w-12 h-12 rounded-2xl bg-amber-100 text-amber-700 flex items-center justify-center mx-auto shadow-inner">
                <Undo2 className="w-6 h-6" />
              </div>

              <div className="text-center space-y-1.5">
                <h3 className="text-base font-bold text-slate-900">Void Salary Payment?</h3>
                <p className="text-xs text-slate-500">
                  Are you sure you want to void the salary payout of <strong className="text-slate-800">Rs. {paymentToDelete.amountPaid.toLocaleString()}</strong> for <strong className="text-slate-800">{paymentToDelete.staffName}</strong> ({paymentToDelete.monthName || paymentToDelete.month})?
                </p>
                <div className="text-[11px] text-emerald-700 font-semibold bg-emerald-50 p-2.5 rounded-xl border border-emerald-200 mt-2">
                  This will delete the expense document and restore the money back to the branch profit & ledger.
                </div>
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setPaymentToDelete(null)}
                  className="w-1/2 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold text-xs transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={() => handleVoidSalaryPayment(paymentToDelete)}
                  disabled={loading}
                  className="w-1/2 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded-xl font-bold text-xs transition-colors cursor-pointer shadow-sm disabled:opacity-50"
                >
                  {loading ? 'Reverting...' : 'Confirm & Restore Money'}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: DELETE STAFF ACCOUNT CONFIRMATION */}
      <AnimatePresence>
        {staffToDelete && (
          <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-xs flex items-center justify-center p-4 z-50">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-sm w-full p-6 shadow-2xl border border-slate-200 space-y-4"
            >
              <div className="w-12 h-12 rounded-2xl bg-rose-100 text-rose-600 flex items-center justify-center mx-auto shadow-inner">
                <Trash2 className="w-6 h-6" />
              </div>

              <div className="text-center space-y-1.5">
                <h3 className="text-base font-black text-slate-900">Delete Staff Account?</h3>
                <p className="text-xs text-slate-500">
                  Are you sure you want to permanently remove staff member <strong className="text-slate-900 font-extrabold">{staffToDelete.name}</strong> (<span className="font-mono text-orange-600">@{staffToDelete.username}</span>)?
                </p>
                <div className="bg-rose-50 text-rose-800 p-2.5 rounded-xl border border-rose-200 text-xs font-medium mt-2">
                  Role: {staffToDelete.role} • This will permanently remove their login credentials.
                </div>
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setStaffToDelete(null)}
                  disabled={loading}
                  className="w-1/2 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold text-xs transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={confirmDeleteStaff}
                  disabled={loading}
                  className="w-1/2 py-2 bg-rose-600 hover:bg-rose-700 text-white rounded-xl font-bold text-xs transition-colors cursor-pointer shadow-sm disabled:opacity-50"
                >
                  {loading ? 'Deleting...' : 'Yes, Delete Staff'}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: VIEW BILLS & REVENUE GENERATED BY STAFF / SESSION */}
      <AnimatePresence>
        {viewingBillsModal && (
          <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-xs flex items-center justify-center p-4 z-50 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl max-w-2xl w-full p-6 shadow-2xl border border-slate-200 space-y-4 my-8"
            >
              {/* Modal Header */}
              <div className="flex items-start justify-between border-b border-slate-100 pb-4">
                <div className="flex items-start gap-3">
                  <div className="w-11 h-11 rounded-2xl bg-blue-50 text-blue-700 flex items-center justify-center font-black text-base shrink-0 shadow-inner">
                    <Receipt className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-black text-slate-900 leading-tight">
                      {viewingBillsModal.title}
                    </h3>
                    <div className="flex flex-wrap items-center gap-2 mt-1">
                      {/* Role Badge */}
                      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-lg text-[10px] font-extrabold border ${
                        getRoleInfo(viewingBillsModal.role).badgeClass
                      }`}>
                        {getRoleInfo(viewingBillsModal.role).shortLabel}
                      </span>

                      {/* Online/Offline Status */}
                      {viewingBillsModal.isOnline ? (
                        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-lg bg-emerald-100 text-emerald-900 font-extrabold text-[10px] border border-emerald-300">
                          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                          <span>ROLE ONLINE</span>
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-lg bg-slate-100 text-slate-600 font-bold text-[10px] border border-slate-200">
                          <span className="w-1.5 h-1.5 rounded-full bg-slate-400" />
                          <span>ROLE OFFLINE</span>
                        </span>
                      )}

                      {viewingBillsModal.counterInfo && (
                        <span className="text-[11px] text-slate-400 font-medium">
                          • {viewingBillsModal.counterInfo}
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => setViewingBillsModal(null)}
                  className="p-1 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* KPI Summary Strip */}
              <div className="grid grid-cols-2 gap-3 bg-gradient-to-r from-slate-50 to-emerald-50/40 p-3.5 rounded-2xl border border-slate-200">
                <div>
                  <span className="text-[11px] font-bold text-slate-500 block">Total Bills Generated</span>
                  <div className="text-xl font-black text-slate-900 mt-0.5">
                    {viewingBillsModal.totalBills} <span className="text-xs font-normal text-slate-400">bills</span>
                  </div>
                </div>

                <div className="border-l border-slate-200 pl-4">
                  <span className="text-[11px] font-bold text-slate-500 block">Total Revenue Generated</span>
                  <div className="text-xl font-black text-emerald-700 font-mono mt-0.5">
                    Rs. {viewingBillsModal.totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                </div>
              </div>

              {/* Bills List / Table */}
              <div className="max-h-80 overflow-y-auto border border-slate-200 rounded-2xl overflow-hidden">
                {viewingBillsModal.sales.length === 0 ? (
                  <div className="p-8 text-center text-slate-400 text-xs">
                    <Receipt className="w-8 h-8 mx-auto text-slate-300 mb-2" />
                    <p className="font-bold text-slate-700">No Individual Bills Logged</p>
                    <p className="mt-1">Bills completed through the cash counter will list here automatically.</p>
                  </div>
                ) : (
                  <table className="w-full text-left text-xs border-collapse">
                    <thead className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200 sticky top-0">
                      <tr>
                        <th className="p-3">Bill / Receipt #</th>
                        <th className="p-3">Date & Time</th>
                        <th className="p-3">Items</th>
                        <th className="p-3 text-right">Amount (Rs.)</th>
                        <th className="p-3 text-center w-24">Receipt</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {viewingBillsModal.sales.map(sale => {
                        const dateFormatted = new Date(sale.timestamp).toLocaleString([], {
                          dateStyle: 'short',
                          timeStyle: 'short'
                        });
                        const itemsCount = sale.items?.reduce((sum, item) => sum + (item.quantity || 1), 0) || 0;

                        return (
                          <tr key={sale.id} className="hover:bg-slate-50 transition-colors">
                            <td className="p-3 font-mono font-bold text-slate-900">
                              #{sale.id.slice(-6).toUpperCase()}
                            </td>
                            <td className="p-3 text-slate-600 font-mono">
                              {dateFormatted}
                            </td>
                            <td className="p-3 text-slate-600">
                              <span className="font-medium text-slate-800">{itemsCount}</span> items
                            </td>
                            <td className="p-3 text-right font-mono font-black text-emerald-700">
                              Rs. {Number(sale.totalAmount || 0).toFixed(2)}
                            </td>
                            <td className="p-3 text-center">
                              <button
                                type="button"
                                onClick={() => setSelectedReceiptSale(sale)}
                                className="px-2.5 py-1 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-800 text-[11px] font-bold border border-emerald-200 transition-colors cursor-pointer"
                              >
                                View Slip
                              </button>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                )}
              </div>

              {/* Close Button */}
              <div className="flex items-center justify-end pt-2">
                <button
                  type="button"
                  onClick={() => setViewingBillsModal(null)}
                  className="px-5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-xl font-bold text-xs cursor-pointer transition-colors"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: CUSTOMER RECEIPT SLIP PREVIEW */}
      {selectedReceiptSale && (
        <ReceiptModal
          isOpen={Boolean(selectedReceiptSale)}
          onClose={() => setSelectedReceiptSale(null)}
          sale={selectedReceiptSale}
          store={store}
        />
      )}

    </div>
  );
};
